---
# handlers file for spire_agent
- name: 'Restart spire-agent'
  ansible.builtin.include_tasks: service.yml
  vars:
    instance_state: restarted
  listen: "restart_spire_agent"

- name: "Perform daemon-reload"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
